### ISSUE TITLE
rigify error

### ISSUE THREAD

**Issue by loicbramoulle** [soupday/CC4-Blender-Tools-Plugin#14]
Hi, I'm trying to rigify the default kevin CC4 character, so using the pipeline as usual, lastest version for both CCplugin & blender addon, but I keep getting an error during the rigify process, it stops and I can just see the facial bones, even if I don't ask to create facial. I remembered that it just worked when clicking rigify, I'm doing anything special now. Thanks for any help.

  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cc_blender_tools-1_6_0_4\rigging.py", line 3646, in execute
    self.rigify_meta_rig(chr_cache)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cc_blender_tools-1_6_0_4\rigging.py", line 3509, in rigify_meta_rig
    bpy.ops.pose.rigify_generate()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Generation has thrown an exception: bpy_prop_collection[index]: index 0 out of range, size 0
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

Error: Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cc_blender_tools-1_6_0_4\importer.py", line 1059, in modal
    self.run_finish(context)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cc_blender_tools-1_6_0_4\importer.py", line 1019, in run_finish
    bpy.ops.cc3.rigifier(param="ALL")
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cc_blender_tools-1_6_0_4\rigging.py", line 3646, in execute
    self.rigify_meta_rig(chr_cache)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cc_blender_tools-1_6_0_4\rigging.py", line 3509, in rigify_meta_rig
    bpy.ops.pose.rigify_generate()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Generation has thrown an exception: bpy_prop_collection[index]: index 0 out of range, size 0
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

**Comment by loicbramoulle** [comment]
Oww ok it works in 3.5, so 3.6 is not yet supported as I understand.

**Comment by soupday** [comment]
It works in 3.6 too, just tried it in 3.6.4 and it worked no problems on Kevin.

But that's an odd place to crash. It's crashing in the rigify operator itself. Does Rigify work correctly in 3.6 if you just add a Human meta-rig armature and generate the rigify rig from that manually?

**Comment by loicbramoulle** [comment]
Ow indeed, I just tried to add a meta rig and generate rigify rig on it, and it crashes, so something must be broken in my rigify addon or something. odd that it's only on 3.6.1, 3.6.3, not in 3.5. hope it won't carry over 4.0, I thnk with time we accumulate errors in our preferences, like I can't open side anim editors panels anymore if they're closed, my autosaves regularly stop saving and only way is to restore a pref file from a few months back. Or maybe it's one addon that does this kind of things.
